spring:
  application:
    name: springcloud-config-eureka-dept
  profiles:
    active: dev
server:
  port: 8001
eureka:
  client:
    service-url:
      defuatlZone: http://localhost:8888/eureka/
---
spring:
  application:
    name: springcloud-config-eureka-dept
  profiles:
    active: text
server:
  port: 8001
eureka:
  client:
    service-url:
      defuatlZone: http://localhost:8888/eureka/
