spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka-dept
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=GMT%2B8
server:
  port: 8001
eureka:
  client:
   service-url:
       defaultZone: http://localhost:8888/eureka/
   instance:
       hostname: dept-8001.com
       prefer-ip-address: true
mybatis-puls:
   mapper-locations: classpath:Mapper/*.xml
   type-aliases-package: com.example.Pojo
---
spring:
  profiles: test
  application:
    name: springcloud-config-eureka-dept
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=GMT%2B8

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: dept-8001.com
    prefer-ip-address: true
mybatis-puls:
   mapper-locations: classpath:Mapper/*.xml
   type-aliases-package: com.example.Pojo
