spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka-dept
server:
  port: 8001
eureka:
  client:
   service-url:
       defaultZone: http://localhost:8888/eureka/
   instance:
       hostname: dept-8001.com
       prefer-ip-address: true
---
spring:
  profiles: test
  application:
    name: springcloud-config-eureka-dept
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: dept-8001.com
    prefer-ip-address: true